export const ORDER_ARTISTS_SUCCESS = 'ORDER_ARTISTS_SUCCESS';
export const ORDER_ARTISTS_ERROR = 'ORDER_ARTISTS_ERROR';
export const ORDER_ARTISTS_REQUEST = 'ORDER_ARTISTS_REQUEST';

export const ORDER_ALBUMS_SUCCESS = 'ORDER_ALBUMS_SUCCESS';
export const ORDER_ALBUMS_ERROR  = 'ORDER_ALBUMS_ERROR';
export const ORDER_ALBUMS_REQUEST = 'ORDER_ALBUMS_REQUEST';

export const ORDER_TRACKS_SUCCESS = 'ORDER_TRACKS_SUCCESS';
export const ORDER_TRACKS_ERROR  = 'ORDER_TRACKS_ERROR';
export const ORDER_TRACKS_REQUEST = 'ORDER_TRACKS_REQUEST';

export const ORDER_ARTIST = 'ORDER_ARTIST';
export const ORDER_ALBUM = 'ORDER_ALBUM';

export const ORDER_REGISTER_SUCCESS = 'ORDER_REGISTER_SUCCESS';
export const ORDER_REGISTER_REQUEST = 'ORDER_REGISTER_REQUEST';
export const ORDER_REGISTER_ERROR = 'ORDER_REGISTER_ERROR';


export const ORDER_LOGIN_SUCCESS = 'ORDER_LOGIN_SUCCESS';
export const ORDER_LOGIN_REQUEST = 'ORDER_LOGIN_REQUEST';
export const ORDER_LOGIN_ERROR = 'ORDER_LOGIN_ERROR';


export const ORDER_TRACK_HISTORY_SUCCESS = 'ORDER_TRACK_HISTORY_SUCCESS';
export const ORDER_TRACK_HISTORY_REQUEST = 'ORDER_TRACK_HISTORY_REQUEST';
export const ORDER_TRACK_HISTORY_ERROR = 'ORDER_TRACK_HISTORY_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS';
export const ADD_ARTIST_REQUEST = 'ADD_ARTIST_REQUEST';
export const ADD_ARTIST_ERROR = 'ADD_ARTIST_ERROR';


export const ADD_ALBUM_SUCCESS = 'ADD_ALBUM_SUCCESS';
export const ADD_ALBUM_REQUEST = 'ADD_ALBUM_REQUEST';
export const ADD_ALBUM_ERROR = 'ADD_ALBUM_ERROR';

export const ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS';
export const ADD_TRACK_REQUEST = 'ADD_TRACK_REQUEST';
export const ADD_TRACK_ERROR = 'ADD_TRACK_ERROR';

export const ORDER_ALL_ALBUMS_SUCCESS = 'ORDER_ALL_ALBUMS_SUCCESS';
export const ORDER_ALL_ALBUMS_REQUEST = 'ORDER_ALL_ALBUMS_REQUEST';
export const ORDER_ALL_ALBUMS_ERROR = 'ORDER_ALL_ALBUMS_ERROR';

export const LOGIN_FB_USER_SUCCESS = 'LOGIN_FB_USER_SUCCESS';
export const LOGIN_FB_USER_REQUEST = 'LOGIN_FB_USER_REQUEST';
export const LOGIN_FB_USER_ERROR = 'LOGIN_FB_USER_ERROR';


